"""empty message

Revision ID: 17692a810923
Revises: 86e51121da0c
Create Date: 2019-05-01 15:24:02.107400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17692a810923'
down_revision = '86e51121da0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
